routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapelController;
use App\Http\Controllers\DataguruController;
use App\Http\Controllers\DatakelasController;
use App\Http\Controllers\TahunajaranController;
use App\Http\Controllers\AngkatanController;
use App\Http\Controllers\DatasiswaController;
use App\Http\Controllers\SesiController;
use App\Http\Controllers\GurumapelController;
use App\Http\Controllers\RombelController;
use App\Http\Controllers\DatajadwalController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\JadwalguruController;
use App\Http\Controllers\PresensiController;
use App\Http\Controllers\DatakepegController;
use App\Http\Controllers\PendinformalController;
use App\Http\Controllers\PendformalController;
use App\Http\Controllers\RpekerjaanController;
use App\Http\Controllers\PenghargaanController;
use App\Http\Controllers\KetorganisasiController;
use App\Http\Controllers\KetlainController;
use App\Http\Controllers\WalikelasController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\DatauserController;
use App\Http\Controllers\JadwalsiswaController;
use App\Http\Controllers\KelasguruController;
use App\Http\Controllers\KontaksiswaController;
use App\Http\Controllers\NilaisiswaController;
use App\Http\Controllers\PresensisiswaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RkeluargaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

//login
// Route::resource('login', AuthController::class);
Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('aktivasi_akun', 'App\Http\Controllers\AuthController@aktivasi_akun')->name('aktivasi_akun');
Route::get('lupapassword', 'App\Http\Controllers\AuthController@index_lupapassword')->name('lupapassword');
Route::post('forgot_password', 'App\Http\Controllers\AuthController@forgot_password')->name('forgot_password');
Route::get('reset_password', 'App\Http\Controllers\AuthController@reset_password')->name('reset_password');
Route::post('new_password', 'App\Http\Controllers\AuthController@new_password')->name('new_password');


//auth
//auth -> admin || guru || siswa

Route::group(['middleware' => ['auth']], function () {
    Route::resource('profile', ProfileController::class);
    Route::group(['middleware' => ['Cek_login:admin']], function () {
        Route::get('dashboardadmin', 'App\Http\Controllers\AdminController@index');
        //route admin
        Route::resource('dashboardadmin', AdminController::class);
        //admin : Mapel
        Route::resource('mapel', MapelController::class);
        //admin : guru
        Route::resource('guru', DataguruController::class);
        //admin : siswa
        Route::resource('siswa', DatasiswaController::class);
        //admin : kelas
        Route::resource('kelas', DatakelasController::class);
        //admin : angkatan
        Route::resource('angkatan', AngkatanController::class);
        //admin : tahun ajaran
        Route::resource('tahunajaran', TahunajaranController::class);
        //admin : sesi
        Route::resource('sesi', SesiController::class);
        //admin : guru mapel
        Route::resource('gurumapel', GurumapelController::class);
        //admin : rombel
        Route::resource('rombel', RombelController::class);
        //admin : jadwal
        Route::resource('jadwal', DatajadwalController::class);
        Route::get('hapus', 'App\Http\Controllers\DataJadwalController@hapus')->name('jadwal.hapus');
        //admin : walikelas
        Route::resource('walikelas', WalikelasController::class);
        //admin : kepegawaian
        Route::resource('kepeg', DatakepegController::class);
        //admin : user
        Route::resource('datauser', DatauserController::class);
    });
    Route::group(['middleware' => ['Cek_login:guru']], function () {
        Route::get('dashboardguru', 'App\Http\Controllers\GuruController@index')->name('dashboardguru.index');
        Route::resource('jadwalguru', JadwalguruController::class);
        Route::resource('presensi', PresensiController::class);
        Route::get('rekapharian', 'App\Http\Controllers\PresensiController@rekapharian')->name('presensi.rekapharian');
        Route::get('allrekap', 'App\Http\Controllers\PresensiController@allrekap')->name('presensi.allrekap');
        Route::get('indexallrekap', 'App\Http\Controllers\PresensiController@indexallrekap')->name('presensi.indexallrekap');
        Route::resource('kepegawaian', DatakepegController::class);
        Route::resource('pendinformal', PendinformalController::class);
        Route::resource('pendformal', PendformalController::class);
        Route::resource('riwayatpekerjaan', RpekerjaanController::class);
        Route::resource('penghargaan', PenghargaanController::class);
        Route::resource('ketorganisasi', KetorganisasiController::class);
        Route::resource('ketlain', KetlainController::class);
        Route::resource('nilai', NilaiController::class);
        Route::resource('kelasguru', KelasguruController::class);
        Route::resource('riwayatkeluarga', RkeluargaController::class);
        Route::resource('infokontak', KontaksiswaController::class);
        Route::resource('datanilaisiswa', NilaiController::class);
        Route::post('deskripsi', 'App\Http\Controllers\NilaiController@deskripsi')->name('datanilaisiswa.deskripsi');
    });
    Route::group(['middleware' => ['Cek_login:siswa']], function () {
        Route::get('dashboardsiswa', 'App\Http\Controllers\SiswaController@index')->name('dashboardsiswa.index');
        Route::resource('jadwalsiswa', JadwalsiswaController::class);
        Route::resource('presensisiswa', PresensisiswaController::class);
        Route::resource('nilaisiswa', NilaisiswaController::class);
        Route::get('cetakrapot', 'App\Http\Controllers\NilaisiswaController@cetakpdf')->name('nilaisiswa.cetakrapot');
    });
});

app/Http/Controllers/GuruController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id_guru = Auth::user()->id;

        $pend_formal = DB::table('pend_formal')
            ->join('guru', 'guru.id', 'pend_formal.id_guru')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $pend_informal = DB::table('pend_informal')
            ->join('guru', 'guru.id', 'pend_informal.id_guru')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $riwayat_pekerjaan = DB::table('riwayat_pekerjaan')
            ->join('guru', 'guru.id', 'riwayat_pekerjaan.id_guru')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $penghargaan = DB::table('penghargaan')
            ->join('guru', 'guru.id', 'penghargaan.id_guru')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $organisasi = DB::table('organisasi_guru')
            ->join('guru', 'guru.id', 'organisasi_guru.id_guru')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $keteranganlain = DB::table('keterangan_lain')
            ->join('guru', 'guru.id', 'keterangan_lain.id_guru')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $jumlahsiswa = DB::table('angkatan')
            ->join('walikelas', 'angkatan.id', 'walikelas.id_angkatan')
            ->join('guru', 'walikelas.id_guru', 'guru.id')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        $jumlahmapel = DB::table('mapel')
            ->join('gurumapel', 'mapel.id', 'gurumapel.id_mapel')
            ->join('guru', 'gurumapel.id_guru', 'guru.id')
            ->where('guru.id_user', '=', $id_guru)
            ->count();

        // echo $jumlahsiswa;
        // exit;
        return view('guru.guru')->with([
            'countpend_formal' => $pend_formal,
            'countpend_informal' => $pend_informal,
            'countrpekerjaan' => $riwayat_pekerjaan,
            'countpenghargaan' => $penghargaan,
            'countorganisasi_guru' => $organisasi,
            'countketerangan_lain' => $keteranganlain,
            'countjumlahsiswa' => $jumlahsiswa,
            'countjumlahmapel' => $jumlahmapel
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/guru/editketlain.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Data Pendidikan Informal</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('ketlain.update',['ketlain'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Nama Ketarangan</label>
                    <select name="nama_keterangan" class="form-control">
                        <option></option>
                        <option Surat value="skck" {{$data->nama_keterangan == 'skck' ? 'selected' : ''}}>Surat
                            Keterangan Catatan Kepolisian</option>
                        <option value="sks" {{$data->nama_keterangan == 'sks' ? 'selected' : ''}}>Surat Keterangan Sehat
                        </option>
                        <option value="skbn" {{$data->nama_keterangan == 'skbn' ? 'selected' : ''}}>Surat Keterangan
                            Bebas Napza</option>
                        <option value="lainnya" {{$data->nama_keterangan == 'lainnya' ? 'selected' : ''}}>Keterangan
                            lain yang Dianggap Perlu</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Nomor Surat Keputusan</label>
                    <input type="text" name="nomor_sk" class="form-control" placeholder="Nomor Surat Keputusan"
                        value="{{$data->nomor_sk}}">
                </div>
                <div class="form-group">
                    <label>Tanggal Surat Keputusan</label>
                    <input type="date" name="tgl_sk" class="form-control" value="{{$data->tgl_sk}}">
                </div>

                <div class="form-group">
                    <label>Pejabat</label>
                    <input type="text" name="pejabat" class="form-control" placeholder="Nama Pejabat"
                        value="{{$data->pejabat}}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/guru/editpendformal.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Edit Data Pendidikan Informal</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('pendformal.update',['pendformal'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Tingkat</label>
                    <input type="text" name="tingkat" class="form-control" placeholder="Tingkat"
                        value="{{$data->tingkat}}">
                </div>
                <div class="form-group">
                    <label>Nama Sekolah/Perguruan Negeri</label>
                    <input type="text" name="nama_sekolah" class="form-control"
                        placeholder="Nama Sekolah / Perguruan Negeri" value="{{$data->nama_sekolah}}">
                </div>
                <div class="form-group">
                    <label>Akreditasi</label>
                    <input type="text" name="akreditasi" class="form-control" placeholder="Akreditasi"
                        value="{{$data->akreditasi}}">
                </div>
                <div class="form-group">
                    <label>Tempat</label>
                    <input type="text" name="tempat" class="form-control" placeholder="Tempat"
                        value="{{$data->tempat}}">
                </div>
                <div class="form-group">
                    <label>Nomor</label>
                    <input type="text" name="nomor_ijazah" class="form-control" placeholder="Nomor"
                        value="{{$data->nomor_ijazah}}">
                </div>
                <div class="form-group">
                    <label>Tanggal</label>
                    <input type="date" name="tanggal" class="form-control" placeholder="Tanggal Kelulusan"
                        value="{{$data->tanggal}}">
                </div>
                <div class="form-group">
                    <label>Pejabat Penandatangan</label>
                    <input type="text" name="pejabat_ttd" class="form-control" placeholder="Pejabat Penandatangan"
                        value="{{$data->pejabat_ttd}}">
                </div>
                <div class="form-group">
                    <label>Gelar Depan</label>
                    <input type="text" name="gelar_depan" class="form-control" placeholder="Gelar Depan"
                        value="{{$data->gelar_depan}}">
                </div>
                <div class="form-group">
                    <label>Gelar Belakang</label>
                    <input type="text" name="gelar_belakang" class="form-control" placeholder="Gelar Belakang"
                        value="{{$data->gelar_belakang}}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/guru/editpenghargaan.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Data Tanda Jasa/Penghargaan</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('penghargaan.update',['penghargaan'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Nama Bintang/Lencana Penghargaan</label>
                    <input type="text" name="nama_penghargaan" class="form-control" placeholder="Nama Penghargaan"
                        value="{{$data->nama_penghargaan}}">
                </div>
                <div class="form-group">
                    <label>Nomor Surat Keputusan</label>
                    <input type="text" name="nomor_sk" class="form-control" placeholder="Nomor Surat Keputusan"
                        value="{{$data->nomor_sk}}">
                </div>
                <div class="form-group">
                    <label>Tanggal Surat Keputusan</label>
                    <input type="date" name="tgl_sk" class="form-control" value="{{$data->tgl_sk}}">
                </div>
                <div class="form-group">
                    <label>Tahun</label>
                    <input type="text" name="tahun" class="form-control" placeholder="Tahun" value="{{$data->tahun}}">
                </div>
                <div class="form-group">
                    <label>Nama Negara/Instansi yang memberikan</label>
                    <input type="text" name="nama_instansi" class="form-control" placeholder="Nama Instansi"
                        value="{{$data->nama_instansi}}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/guru/editriwayatpekerjaan.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Data Riwayat Pekerjaan</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('riwayatpekerjaan.update',['riwayatpekerjaan'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Nama Instansi / Perusahaan</label>
                    <input type="text" name="instansi" class="form-control" placeholder="Nama Instansi /Perusahaan"
                        value="{{$data->instansi}}">
                </div>
                <div class="form-group">
                    <label>Jabatan</label>
                    <input type="text" name="jabatan" class="form-control" placeholder="Jabatan"
                        value="{{$data->jabatan}}">
                </div>
                <div class="form-group">
                    <label>Tanggal Mulai</label>
                    <input type="date" name="tgl_mulai" class="form-control" value="{{$data->tgl_mulai}}">
                </div>
                <div class="form-group">
                    <label>Tanggal Selesai</label>
                    <input type="date" name="tgl_selesai" class="form-control" value="{{$data->tgl_selesai}}">
                </div>

                <div class="form-group">
                    <label>Gaji Pokok</label>
                    <input type="text" name="gaji_pokok" class="form-control" placeholder="Gaji Pokok"
                        value="{{$data->gaji_pokok}}">
                </div>
                <div class="form-group">
                    <label>Nomor Surat Keputasan</label>
                    <input type="text" name="nomor_sk" class="form-control" placeholder="Nomor Surat Keputusan"
                        value="{{$data->nomor_sk}}">
                </div>
                <div class="form-group">
                    <label>Tanggal Surat Keputasan</label>
                    <input type="date" name="tgl_sk" class="form-control" placeholder="Tanggal Surat Keputusan"
                        value="{{$data->tgl_sk}}">
                </div>
                <div class="form-group">
                    <label>Pejabat Penandatangan SK</label>
                    <input type="text" name="pejabat_ttd" class="form-control"
                        placeholder="Pejabat Penandatangan Surat Keputusan" value="{{$data->pejabat_ttd}}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/guru/pendformal.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Pendidikan Formal</h1>
    </div>

    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">

                <a href="{{route('kepegawaian.index')}}" class="btn btn-warning fas fa-angle-left"> Kembali</a>
                <a href="{{route('pendformal.create')}}" class="btn btn-primary fa fa-plus"
                    style="position: absolute; right:25px;"> Tambah Data</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-md datatable_table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Tingkat</th>
                                <th>Nama Sekolah/Perguruan Negeri</th>
                                <th>Akreditasi</th>
                                <th>Tempat</th>
                                <th>Nomor Ijazah</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @foreach ($data as $formal)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{$formal->tingkat }}</td>
                                <td>{{$formal->nama_sekolah}}</td>
                                <td>{{$formal->akreditasi}}</td>
                                <td>{{$formal->tempat}}</td>
                                <td>{{$formal->nomor_ijazah}}</td>
                                <td>
                                    <form method="POST"
                                        action="{{route('pendformal.destroy',['pendformal'=>$formal->id])}}">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{route('pendformal.edit',['pendformal'=>$formal->id])}}"
                                            class="btn btn-icon btn-left btn-warning"><i class="far fa-edit"></i>
                                            Edit</a>
                                        <button type="submit" class="btn btn-icon btn-left btn-danger"><i
                                                class="fas fa-times"></i>
                                            Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>



@endsection

resources/views/guru/tambahketlain.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Data Pendidikan Informal</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('ketlain.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label>Nama Ketarangan</label>
                    <select name="nama_keterangan" class="form-control">
                        <option></option>
                        <option value="skck">Surat Keterangan Catatan Kepolisian</option>
                        <option value="sks">Surat Keterangan Sehat</option>
                        <option value="skbn">Surat Keterangan Bebas Napza</option>
                        <option value="lainnya">Keterangan lain yang Dianggap Perlu</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Nomor Surat Keputusan</label>
                    <input type="text" name="nomor_sk" class="form-control" placeholder="Nomor Surat Keputusan"
                        required>
                </div>
                <div class="form-group">
                    <label>Tanggal Surat Keputusan</label>
                    <input type="date" name="tgl_sk" class="form-control" required>
                </div>

                <div class="form-group">
                    <label>Pejabat</label>
                    <input type="text" name="pejabat" class="form-control" placeholder="Nama Pejabat" required>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/guru/tambahketorganisasi.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Data Keterangan Organisasi</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('ketorganisasi.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label>Nama Organisasi</label>
                    <input type="text" name="nama_organisasi" class="form-control" placeholder="Nama Organisasi"
                        required>
                </div>
                <div class="form-group">
                    <label>Jabatan</label>
                    <input type="text" name="jabatan" class="form-control" placeholder="Jabatan" required>
                </div>
                <div class="form-group">
                    <label>Tanggal Mulai</label>
                    <input type="date" name="tgl_mulai" class="form-control" required>
                </div>
                <div class="form-group">
                    <label>Tanggal Selesai</label>
                    <input type="date" name="tgl_selesai" class="form-control" required>
                </div>

                <div class="form-group">
                    <label>Tempat</label>
                    <input type="text" name="tempat" class="form-control" placeholder="Tempat Organisasi" required>
                </div>
                <div class="form-group">
                    <label>Pemimpin Organisasi</label>
                    <input type="text" name="pemimpin" class="form-control" placeholder="Pemimpin Organisasi" required>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/guru/tambahpendformal.blade.php
@extends('layout.master')
@extends('layout.sidebarguru')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Data Pendidikan Informal</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('pendformal.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label>Tingkat</label>
                    <input type="text" name="tingkat" class="form-control" placeholder="Tingkat" required>
                </div>
                <div class="form-group">
                    <label>Nama Sekolah/Perguruan Negeri</label>
                    <input type="text" name="nama_sekolah" class="form-control"
                        placeholder="Nama Sekolah / Perguruan Negeri" required>
                </div>
                <div class="form-group">
                    <label>Akreditasi</label>
                    <input type="text" name="akreditasi" class="form-control" placeholder="Akreditasi" required>
                </div>
                <div class="form-group">
                    <label>Tempat</label>
                    <input type="text" name="tempat" class="form-control" placeholder="Tempat" required>
                </div>
                <div class="form-group">
                    <label>Nomor</label>
                    <input type="text" name="nomor_ijazah" class="form-control" placeholder="Nomor" required>
                </div>
                <div class="form-group">
                    <label>Tanggal</label>
                    <input type="date" name="tanggal" class="form-control" placeholder="Tanggal Kelulusan" required>
                </div>
                <div class="form-group">
                    <label>Pejabat Penandatangan</label>
                    <input type="text" name="pejabat_ttd" class="form-control" placeholder="Pejabat Penandatangan"
                        required>
                </div>
                <div class="form-group">
                    <label>Gelar Depan</label>
                    <input type="text" name="gelar_depan" class="form-control" placeholder="Gelar Depan" required>
                </div>
                <div class="form-group">
                    <label>Gelar Belakang</label>
                    <input type="text" name="gelar_belakang" class="form-control" placeholder="Gelar Belakang" required>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection