routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapelController;
use App\Http\Controllers\DataguruController;
use App\Http\Controllers\DatakelasController;
use App\Http\Controllers\TahunajaranController;
use App\Http\Controllers\AngkatanController;
use App\Http\Controllers\DatasiswaController;
use App\Http\Controllers\SesiController;
use App\Http\Controllers\GurumapelController;
use App\Http\Controllers\RombelController;
use App\Http\Controllers\DatajadwalController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\JadwalguruController;
use App\Http\Controllers\PresensiController;
use App\Http\Controllers\DatakepegController;
use App\Http\Controllers\PendinformalController;
use App\Http\Controllers\PendformalController;
use App\Http\Controllers\RpekerjaanController;
use App\Http\Controllers\PenghargaanController;
use App\Http\Controllers\KetorganisasiController;
use App\Http\Controllers\KetlainController;
use App\Http\Controllers\WalikelasController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\DatauserController;
use App\Http\Controllers\JadwalsiswaController;
use App\Http\Controllers\KelasguruController;
use App\Http\Controllers\KontaksiswaController;
use App\Http\Controllers\NilaisiswaController;
use App\Http\Controllers\PresensisiswaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RkeluargaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

//login
// Route::resource('login', AuthController::class);
Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('aktivasi_akun', 'App\Http\Controllers\AuthController@aktivasi_akun')->name('aktivasi_akun');
Route::get('lupapassword', 'App\Http\Controllers\AuthController@index_lupapassword')->name('lupapassword');
Route::post('forgot_password', 'App\Http\Controllers\AuthController@forgot_password')->name('forgot_password');
Route::get('reset_password', 'App\Http\Controllers\AuthController@reset_password')->name('reset_password');
Route::post('new_password', 'App\Http\Controllers\AuthController@new_password')->name('new_password');


//auth
//auth -> admin || guru || siswa

Route::group(['middleware' => ['auth']], function () {
    Route::resource('profile', ProfileController::class);
    Route::group(['middleware' => ['Cek_login:admin']], function () {
        Route::get('dashboardadmin', 'App\Http\Controllers\AdminController@index');
        //route admin
        Route::resource('dashboardadmin', AdminController::class);
        //admin : Mapel
        Route::resource('mapel', MapelController::class);
        //admin : guru
        Route::resource('guru', DataguruController::class);
        //admin : siswa
        Route::resource('siswa', DatasiswaController::class);
        //admin : kelas
        Route::resource('kelas', DatakelasController::class);
        //admin : angkatan
        Route::resource('angkatan', AngkatanController::class);
        //admin : tahun ajaran
        Route::resource('tahunajaran', TahunajaranController::class);
        //admin : sesi
        Route::resource('sesi', SesiController::class);
        //admin : guru mapel
        Route::resource('gurumapel', GurumapelController::class);
        //admin : rombel
        Route::resource('rombel', RombelController::class);
        //admin : jadwal
        Route::resource('jadwal', DatajadwalController::class);
        Route::get('hapus', 'App\Http\Controllers\DataJadwalController@hapus')->name('jadwal.hapus');
        //admin : walikelas
        Route::resource('walikelas', WalikelasController::class);
        //admin : kepegawaian
        Route::resource('kepeg', DatakepegController::class);
        //admin : user
        Route::resource('datauser', DatauserController::class);
    });
    Route::group(['middleware' => ['Cek_login:guru']], function () {
        Route::get('dashboardguru', 'App\Http\Controllers\GuruController@index')->name('dashboardguru.index');
        Route::resource('jadwalguru', JadwalguruController::class);
        Route::resource('presensi', PresensiController::class);
        Route::get('rekapharian', 'App\Http\Controllers\PresensiController@rekapharian')->name('presensi.rekapharian');
        Route::get('allrekap', 'App\Http\Controllers\PresensiController@allrekap')->name('presensi.allrekap');
        Route::get('indexallrekap', 'App\Http\Controllers\PresensiController@indexallrekap')->name('presensi.indexallrekap');
        Route::resource('kepegawaian', DatakepegController::class);
        Route::resource('pendinformal', PendinformalController::class);
        Route::resource('pendformal', PendformalController::class);
        Route::resource('riwayatpekerjaan', RpekerjaanController::class);
        Route::resource('penghargaan', PenghargaanController::class);
        Route::resource('ketorganisasi', KetorganisasiController::class);
        Route::resource('ketlain', KetlainController::class);
        Route::resource('nilai', NilaiController::class);
        Route::resource('kelasguru', KelasguruController::class);
        Route::resource('riwayatkeluarga', RkeluargaController::class);
        Route::resource('infokontak', KontaksiswaController::class);
        Route::resource('datanilaisiswa', NilaiController::class);
        Route::post('deskripsi', 'App\Http\Controllers\NilaiController@deskripsi')->name('datanilaisiswa.deskripsi');
    });
    Route::group(['middleware' => ['Cek_login:siswa']], function () {
        Route::get('dashboardsiswa', 'App\Http\Controllers\SiswaController@index')->name('dashboardsiswa.index');
        Route::resource('jadwalsiswa', JadwalsiswaController::class);
        Route::resource('presensisiswa', PresensisiswaController::class);
        Route::resource('nilaisiswa', NilaisiswaController::class);
        Route::get('cetakrapot', 'App\Http\Controllers\NilaisiswaController@cetakpdf')->name('nilaisiswa.cetakrapot');
    });
});

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>SIAKAD &mdash; SMP</title>

  @stack('before-style')
  @include('includes.style')
  @stack('after-style')

</head>
@php
use App\Models\M_guru;
use App\Models\M_siswa;
@endphp

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                  class="fas fa-search"></i></a></li>
          </ul>

        </form>
        <ul class="navbar-nav navbar-right">

          <li class="dropdown"><a href="#" data-toggle="dropdown"
              class="nav-link dropdown-toggle nav-link-lg nav-link-user">
              @php
              if (Auth::user()->role=='guru') {
              $data=M_guru::where('id_user',Auth::user()->id)->first();
              $foto=URL::to('/uploads').'/'.$data->foto;
              }
              if (Auth::user()->role=='siswa') {
              $data=M_siswa::where('id_user',Auth::user()->id)->first();
              $foto=URL::to('/uploads').'/'.$data->foto;
              }
              if (Auth::user()->role=='admin') {

              $foto=asset('template/assets/img/avatar/avatar-1.png');
              }
              @endphp
              <img alt="image" src="{{$foto}}" class="rounded-circle mr-1">
              <div class="d-sm-none d-lg-inline-block">{{auth()->user ()->name}}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-title">Logged in 5 min ago</div>
              <a href="{{route('profile.index')}}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
              </a>
              <a href="" class="dropdown-item has-icon">
                <i class="fas fa-key"></i> Lupa Password
              </a>
              <div class="dropdown-divider"></div>
              <a href="{{url('logout')}}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar">
        @yield('sidebar')
      </div>

      <!-- Main Content -->
      <div class="main-content">
        @yield('container')
      </div>
    </div>
  </div>

  @stack('before-script')
  @include('includes.script')
  @stack('after-script')
</body>

</html>

resources/views/layout/sidebar.blade.php
@section('sidebar')
<aside id="sidebar-wrapper">
  <div class="sidebar-brand">
    <a href="index.html">SIAKAD</a>
  </div>
  <div class="sidebar-brand sidebar-brand-sm">
    <a href="index.html">St</a>
  </div>
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li class="nav-item dropdown {{ request()->is('dashboardadmin') ? 'active' : ''}}">
      <a href="{{route('dashboardadmin.index')}}" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
    </li>
    <li class="menu-header">Master Data</li>
    <li
      class="nav-item dropdown {{ request()->is('guru') || request()->is('siswa') || request()->is('kelas') || request()->is('mapel')  || request()->is('tahunajaran') || request()->is('sesi')  ? 'active' : ''}}">
      <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Master
          Data</span></a>
      <ul class="dropdown-menu">
        <li class="{{ request()->is('guru') ? 'active' : ''}}"><a class="nav-link " href="{{route('guru.index')}}">Data
            Guru</a>
        </li>
        <li class="{{ request()->is('siswa') ? 'active' : ''}}"><a class="nav-link "
            href="{{route('siswa.index')}}">Data
            Siswa</a></li>
        <li class="{{ request()->is('kelas') ? 'active' : ''}}"><a class="nav-link" href="{{route('kelas.index')}}">Data
            Kelas</a></li>
        <li class="{{ request()->is('mapel') ? 'active' : ''}}"><a class="nav-link" href="{{route('mapel.index')}}">Data
            Mata
            Pelajaran</a></li>
        <li class="{{ request()->is('tahunajaran') ? 'active' : ''}}"><a class="nav-link"
            href="{{route('tahunajaran.index')}}">Tahun Ajaran</a></li>
        <li class="{{ request()->is('sesi') ? 'active' : ''}}"><a class="nav-link"
            href="{{route('sesi.index')}}">Sesi</a></li>
      </ul>
    </li>

    <li class="menu-header">Data Angkatan</li>
    <li class="nav-item {{ request()->is('angkatan') ? 'active' : ''}}">
      <a href="{{route('angkatan.index')}}" class="nav-link "><i class="fas fa-users"></i> <span>Angkatan</span></a>
    </li>

    <li class="menu-header">Guru Mata Pelajaran</li>
    <li class="nav-item {{ request()->is('gurumapel') ? 'active' : ''}}">
      <a href="{{route('gurumapel.index')}}" class="nav-link "><i class="far fa-user"></i> <span>Guru Mata
          Pelajaran</span></a>
    </li>

    <li class="menu-header">Data Jadwal</li>
    <li class="nav-item {{ request()->is('jadwal') ? 'active' : ''}}">
      <a href="{{route('jadwal.index')}}" class="nav-link "><i class="fas fas fa-columns"></i> <span>Jadwal</span></a>
    </li>


    <li class="menu-header">Management Pengguna</li>
    <li class="nav-item {{ request()->is('datauser') ? 'active' : ''}}">
      <a href="{{route('datauser.index')}}" class="nav-link "><i class="far fa-user"></i> <span>user</span></a>
    </li>

</aside>
@endsection

resources/views/layout/sidebarguru.blade.php
@section('sidebar')
<aside id="sidebar-wrapper">
  <div class="sidebar-brand">
    <a href="index.html">SIAKAD</a>
  </div>
  <div class="sidebar-brand sidebar-brand-sm">
    <a href="index.html">St</a>
  </div>
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li class="nav-item dropdown  {{ request()->is('dashboardguru') ? 'active' : ''}}">
      <a href="{{route('dashboardguru.index')}}" class=" nav-link "><i
          class=" fas fa-fire"></i><span>Dashboard</span></a>
    </li>
    <li class="menu-header">Master Data</li>
    <li
      class="nav-item dropdown {{ request()->is('kepegawaian') || request()->is('jadwalguru') || request()->is('nilai') || request()->is('presensi')  ? 'active' : ''}}">
      <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Master
          Data</span></a>
      <ul class="dropdown-menu">
        <li class="{{ request()->is('kepegawaian') ? 'active' : ''}}"><a class="nav-link"
            href="{{route('kepegawaian.index')}}">Data Kepegawaian</a></li>
        <li class="{{ request()->is('jadwalguru') ? 'active' : ''}}"><a class="nav-link"
            href="{{route('jadwalguru.index')}}">Jadwal</a></li>
        <li class="{{ request()->is('nilai') ? 'active' : ''}}"><a class="nav-link"
            href="{{route('nilai.index')}}">Nilai</a></li>
        <li class="{{ request()->is('presensi') ? 'active' : ''}}"><a class="nav-link"
            href="{{route('presensi.index')}}">Presensi Siswa</a></li>
      </ul>
    </li>

    <li class="menu-header">Rekap Presensi</li>
    <li class="nav-item {{ request()->is('presensi') ? 'active' : ''}}">
      <a href="{{route('presensi.indexallrekap')}}" class="nav-link"><i class="fas fa-book-open"></i><span>Rekap
          Presensi</span></a>
    </li>

    <li class="menu-header">Kelas</li>
    <li class="nav-item {{ request()->is('kelasguru') ? 'active' : ''}}">
      <a href="{{route('kelasguru.index')}}" class=" nav-link "><i class=" fas fa-users"></i><span>kelas</span></a>
    </li>

</aside>
@endsection

resources/views/layout/sidebarsiswa.blade.php
@section('sidebar')
<aside id="sidebar-wrapper">
    <div class="sidebar-brand">
        <a href="index.html">SIAKAD</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
        <a href="index.html">St</a>
    </div>
    <ul class="sidebar-menu">
        <li class="menu-header">Dashboard</li>
        <li class="nav-item {{ request()->is('dashboardsiswa') ? 'active' : ''}}">
            <a href="{{route('dashboardsiswa.index')}}" class=" nav-link "><i
                    class=" fas fa-fire"></i><span>Dashboard</span></a>
        </li>
        <li class="menu-header">Jadwal</li>
        <li class="nav-item {{ request()->is('jadwalsiswa') ? 'active' : ''}}">
            <a href="{{route('jadwalsiswa.index')}}" class="nav-link"><i
                    class="fas fas fa-columns"></i><span>Jadwal</span></a>
        </li>
        <li class="menu-header">Presensi</li>
        <li class="nav-item {{ request()->is('presensisiswa') ? 'active' : ''}}">
            <a href="{{route('presensisiswa.index')}}" class=" nav-link "><i
                    class=" fas fa-book-open"></i><span>Presensi</span></a>
        </li>
        <li class="menu-header">Nilai</li>
        <li class="nav-item {{ request()->is('nilaisiswa') ? 'active' : ''}}">
            <a href="{{route('nilaisiswa.index')}}" class="nav-link"><i
                    class="fas fa-book-reader"></i><span>Nilai</span></a>
        </li>

</aside>
@endsection