routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapelController;
use App\Http\Controllers\DataguruController;
use App\Http\Controllers\DatakelasController;
use App\Http\Controllers\TahunajaranController;
use App\Http\Controllers\AngkatanController;
use App\Http\Controllers\DatasiswaController;
use App\Http\Controllers\SesiController;
use App\Http\Controllers\GurumapelController;
use App\Http\Controllers\RombelController;
use App\Http\Controllers\DatajadwalController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\JadwalguruController;
use App\Http\Controllers\PresensiController;
use App\Http\Controllers\DatakepegController;
use App\Http\Controllers\PendinformalController;
use App\Http\Controllers\PendformalController;
use App\Http\Controllers\RpekerjaanController;
use App\Http\Controllers\PenghargaanController;
use App\Http\Controllers\KetorganisasiController;
use App\Http\Controllers\KetlainController;
use App\Http\Controllers\WalikelasController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\DatauserController;
use App\Http\Controllers\JadwalsiswaController;
use App\Http\Controllers\KelasguruController;
use App\Http\Controllers\KontaksiswaController;
use App\Http\Controllers\NilaisiswaController;
use App\Http\Controllers\PresensisiswaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RkeluargaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

//login
// Route::resource('login', AuthController::class);
Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('aktivasi_akun', 'App\Http\Controllers\AuthController@aktivasi_akun')->name('aktivasi_akun');
Route::get('lupapassword', 'App\Http\Controllers\AuthController@index_lupapassword')->name('lupapassword');
Route::post('forgot_password', 'App\Http\Controllers\AuthController@forgot_password')->name('forgot_password');
Route::get('reset_password', 'App\Http\Controllers\AuthController@reset_password')->name('reset_password');
Route::post('new_password', 'App\Http\Controllers\AuthController@new_password')->name('new_password');


//auth
//auth -> admin || guru || siswa

Route::group(['middleware' => ['auth']], function () {
    Route::resource('profile', ProfileController::class);
    Route::group(['middleware' => ['Cek_login:admin']], function () {
        Route::get('dashboardadmin', 'App\Http\Controllers\AdminController@index');
        //route admin
        Route::resource('dashboardadmin', AdminController::class);
        //admin : Mapel
        Route::resource('mapel', MapelController::class);
        //admin : guru
        Route::resource('guru', DataguruController::class);
        //admin : siswa
        Route::resource('siswa', DatasiswaController::class);
        //admin : kelas
        Route::resource('kelas', DatakelasController::class);
        //admin : angkatan
        Route::resource('angkatan', AngkatanController::class);
        //admin : tahun ajaran
        Route::resource('tahunajaran', TahunajaranController::class);
        //admin : sesi
        Route::resource('sesi', SesiController::class);
        //admin : guru mapel
        Route::resource('gurumapel', GurumapelController::class);
        //admin : rombel
        Route::resource('rombel', RombelController::class);
        //admin : jadwal
        Route::resource('jadwal', DatajadwalController::class);
        Route::get('hapus', 'App\Http\Controllers\DataJadwalController@hapus')->name('jadwal.hapus');
        //admin : walikelas
        Route::resource('walikelas', WalikelasController::class);
        //admin : kepegawaian
        Route::resource('kepeg', DatakepegController::class);
        //admin : user
        Route::resource('datauser', DatauserController::class);
    });
    Route::group(['middleware' => ['Cek_login:guru']], function () {
        Route::get('dashboardguru', 'App\Http\Controllers\GuruController@index')->name('dashboardguru.index');
        Route::resource('jadwalguru', JadwalguruController::class);
        Route::resource('presensi', PresensiController::class);
        Route::get('rekapharian', 'App\Http\Controllers\PresensiController@rekapharian')->name('presensi.rekapharian');
        Route::get('allrekap', 'App\Http\Controllers\PresensiController@allrekap')->name('presensi.allrekap');
        Route::get('indexallrekap', 'App\Http\Controllers\PresensiController@indexallrekap')->name('presensi.indexallrekap');
        Route::resource('kepegawaian', DatakepegController::class);
        Route::resource('pendinformal', PendinformalController::class);
        Route::resource('pendformal', PendformalController::class);
        Route::resource('riwayatpekerjaan', RpekerjaanController::class);
        Route::resource('penghargaan', PenghargaanController::class);
        Route::resource('ketorganisasi', KetorganisasiController::class);
        Route::resource('ketlain', KetlainController::class);
        Route::resource('nilai', NilaiController::class);
        Route::resource('kelasguru', KelasguruController::class);
        Route::resource('riwayatkeluarga', RkeluargaController::class);
        Route::resource('infokontak', KontaksiswaController::class);
        Route::resource('datanilaisiswa', NilaiController::class);
        Route::post('deskripsi', 'App\Http\Controllers\NilaiController@deskripsi')->name('datanilaisiswa.deskripsi');
    });
    Route::group(['middleware' => ['Cek_login:siswa']], function () {
        Route::get('dashboardsiswa', 'App\Http\Controllers\SiswaController@index')->name('dashboardsiswa.index');
        Route::resource('jadwalsiswa', JadwalsiswaController::class);
        Route::resource('presensisiswa', PresensisiswaController::class);
        Route::resource('nilaisiswa', NilaisiswaController::class);
        Route::get('cetakrapot', 'App\Http\Controllers\NilaisiswaController@cetakpdf')->name('nilaisiswa.cetakrapot');
    });
});

resources/views/admin/datajadwal.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Data Jadwal {{$tahunAktif->tahun . '('.$tahunAktif->semester.')'}}</h1>
    </div>

    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-md datatable_table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kelas</th>
                                <th>Tahun Ajaran</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @foreach ($data as $j)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{ $j->nama_kelas }}</td>
                                <td>{{ $j->tahun.'('.$j->semester.')' }}</td>
                                <td>
                                    <a href="{{route('jadwal.create', ['id_angkatan'=>$j->id])}}"
                                        class="btn btn-icon btn-left btn-info"><i class="fas fa-info-circle"></i> Kelola
                                        Jadwal</a>

                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    </div>
</section>



@endsection

resources/views/admin/datakelas.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
  <br>
  <div class="section-header">
    <h1>Data Kelas</h1>
  </div>

  <div class="col-12 col-md-12 col-lg-12">
    <div class="card">
      <div class="card-header">
        <a href="{{route('kelas.create')}}" class="btn btn-primary fa fa-plus" style="position: absolute; right:25px;">
          Tambah Data</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-md datatable_table">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Kelas</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              @php $no = 1; @endphp
              @foreach ($data as $datakelas)
              <tr>
                <td>{{$no++}}</td>
                <td>{{ $datakelas->nama_kelas }}</td>
                <td>
                  <form method="POST" action="{{route('kelas.destroy',['kela'=>$datakelas->id])}}">
                    @csrf
                    @method('DELETE')
                    <a href="{{route('kelas.edit',['kela'=>$datakelas->id])}}"
                      class="btn btn-icon btn-left btn-warning"><i class="far fa-edit"></i> Edit</a>
                    <button type="submit" class="btn btn-icon btn-left btn-danger"><i class="fas fa-times"></i>
                      Delete</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
  </div>
</section>
@endsection

resources/views/admin/datasiswa.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Data Siswa</h1>
    </div>

    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <a href="{{route('siswa.create')}}" class="btn btn-primary fa fa-plus"
                    style="position: absolute; right:25px;"> Tambah Data</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-md datatable_table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>NISN</th>
                                <th>Nama</th>
                                <th>Tanggal Lahir</th>
                                <th>Alamat</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @foreach ($data as $siswa)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{ $siswa->nisn }}</td>
                                <td>{{ $siswa->nama }}</td>
                                <td>{{ $siswa->tempat_lahir }}</td>
                                <td>{{ $siswa->alamat }}</td>
                                <td>{{ $siswa->status }}</td>
                                <td>
                                    <form method="POST" action="{{route('siswa.destroy',['siswa'=>$siswa->id])}}">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{route('siswa.show',['siswa'=>$siswa->id])}}"
                                            class="btn btn-icon btn-left btn-primary"><i class="far fa-eye"></i>
                                            Detail </a>
                                        <a href="{{route('siswa.edit',['siswa'=>$siswa->id])}}"
                                            class="btn btn-icon btn-left btn-warning"><i class="far fa-edit"></i>
                                            Edit</a>
                                        <button type="submit" class="btn btn-icon btn-left btn-danger"><i
                                                class="fas fa-times"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    </div>
</section>

@endsection

resources/views/admin/editangkatan.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Angkatan</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('angkatan.update',['angkatan'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label class="d-block" for="id_tahunajaran">Tahun Ajaran</label>
                    <select class="form-control select2_dropdown" name="id_tahunajaran" id="id_tahunajaran">
                        <option></option>
                        @foreach ($tahunAjaran as $v)
                        <option value="{{ $v->id }}" {{ ($v->id == $data->id_tahunajaran ? 'selected' : '') }}>{{
                            $v->tahun }}</option>
                        @endforeach

                    </select>
                </div>
                <div class="form-group">
                    <label class="d-block" for="id_kelas">Kelas</label>
                    <select class="form-control select2_dropdown" name="id_kelas" id="id_kelas">
                        <option></option>
                        @foreach ($kelas as $k)
                        <option value="{{ $k->id }}" {{ ($k->id == $data->id_kelas ? 'selected' : '') }}>{{
                            $k->nama_kelas }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/admin/editsesi.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Sesi</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('sesi.update', ['sesi'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label class="d-block" for="sesi">Sesi</label>
                    <input type="text" name="sesi" class="form-control" placeholder="Sesi" value="{{$data->sesi}}">
                </div>
                <div class="form-group">
                    <label class="d-block" for="jam_mulai">Jam Mulai</label>
                    <input placeholder="Selected time" type="text" id="jam_mulai" name="jam_mulai"
                        class="form-control timepicker" value="{{$data->jam_mulai}}">
                </div>
                <div class="form-group">
                    <label class="d-block" for="jam_selesai">Jam Selesai</label>
                    <input placeholder="Selected time" type="text" id="jam_selesai" name="jam_selesai"
                        class="form-control timepicker" value="jam{{$data->jam_selesai}}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/admin/edituser.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Edit Data User</h1>
    </div>

    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-body">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link" id="nav-akun-tab" data-toggle="tab" href="#nav-akun" role="tab"
                            aria-controls="nav-akun" aria-selected="false">Data Akun</a>
                </nav>
                <form method="POST" action="{{ route('datauser.update', ['datauser'=>$data->id]) }}"
                    enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-akun" role="tabpanel"
                            aria-labelledby="nav-akun-tab">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" name="email" class="form-control" value="{{$data->email}}"
                                            required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" name="username" class="form-control"
                                            value="{{$data->username}}" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="text" name="password" class="form-control"
                                            value="{{$data->password}}" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                </form>
            </div>

        </div>
</section>

@endsection

resources/views/admin/sesi.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Data Sesi</h1>
    </div>

    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <a href="{{route('sesi.create')}}" class="btn btn-primary fa fa-plus"
                    style="position: absolute; right:25px;"> Tambah Data</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-md datatable_table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Sesi</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @foreach ($data as $s)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{ $s->sesi . ' | ' . $s->jam_mulai .
                                    '-'.$s->jam_selesai}}</td>
                                <td>
                                    <form method="POST" action="{{route('sesi.destroy',['sesi'=>$s->id])}}">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{route('sesi.edit',['sesi'=>$s->id])}}"
                                            class="btn btn-icon btn-left btn-warning"><i class="far fa-edit"></i>
                                            Edit</a>
                                        <button type="submit" class="btn btn-icon btn-left btn-danger"><i
                                                class="fas fa-times"></i>
                                            Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    </div>
</section>



@endsection

resources/views/admin/show.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
  <br>
  <div class="section-header">
    <h1>Edit Data MataPelajaran</h1>
  </div>

  <div class="card">
    <div class="card-body">
      <form action="{{route('mapel.update',['mapel'=>$data->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
          <label>MataPelajaran</label>
          <input type="text" name="matapelajaran" class="form-control" placeholder="Nama Matapelajaran"
            value="{{$data->matapelajaran}}">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</section>

@endsection

resources/views/admin/showsesi.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Angkatan</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('sesi.update', ['sesi'=>$data->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label class="d-block" for="sesi">Sesi</label>
                    <input type="text" name="sesi" class="form-control" placeholder="Sesi" value="{{$data->sesi}}">
                </div>
                <div class="form-group">
                    <label class="d-block" for="jam_mulai">Jam Mulai</label>
                    <input placeholder="Selected time" type="text" id="jam_mulai" name="jam_mulai"
                        class="form-control timepicker" value="{{$data->jam_mulai}}">
                </div>
                <div class="form-group">
                    <label class="d-block" for="jam_selesai">Jam Selesai</label>
                    <input placeholder="Selected time" type="text" id="jam_selesai" name="jam_selesai"
                        class="form-control timepicker" value="jam{{$data->jam_selesai}}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/admin/showuser.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Detail User</h1>
    </div>

    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-body">
                <a href="{{route('datauser.index')}}" class="btn btn-icon icon-left btn-warning"><i
                        class="fas fa-arrow-left"></i>Kembali</a>
                <br>
                <br>
                <div class="table-responsive">
                    <table class="table table-striped table-md datatable_table">
                        <thead>
                        <tbody>
                            <tr>
                                <h2>Detail Data User</h2>
                            </tr>
                            <tr>
                                <td colspan="2" style="text-align:center">
                                    <img src="{{URL::to('/uploads').'/'.$data->foto}}" width="30%">
                                </td>
                            </tr>

                            <tr>
                                <th>Nama</th>
                                <td>{{$users->name}}</td>
                            </tr>
                            <tr>
                                <th>username</th>
                                <td>{{$users->username}}</td>
                            </tr>
                            <tr>
                                <th>Role</th>
                                <td>{{$users->role}}</td>
                            </tr>
                            <tr>
                                <th>status</th>
                                <td>{{$data->status}}</td>
                            </tr>
                        </tbody>
                        </thead>
                    </table>
                </div>
            </div>

        </div>
    </div>
    </div>
</section>



@endsection

resources/views/admin/tambahgurumapel.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
    <br>
    <div class="section-header">
        <h1>Tambah Guru Mapel</h1>
    </div>

    <div class="card">
        <div class="card-body">
            <form action="{{route('gurumapel.store')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label class="d-block" for="id_guru">Guru</label>
                    <select class="form-control select2_dropdown" name="id_guru" id="id_guru">
                        <option></option>
                        @foreach ($id_guru as $v)
                        <option value="{{ $v->id }}">{{ $v->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label class="d-block" for="id_mapel">Mata Pelajaran</label>
                    <select class="form-control select2_dropdown" name="id_mapel" id="id_mapel">
                        <option></option>
                        @foreach ($id_mapel as $k)
                        <option value="{{ $k->id }}">{{ $k->matapelajaran }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <a href="{{route('gurumapel.index')}}" class="btn btn-icon icon-left btn-warning">Kembali</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/admin/tambahmapel.blade.php
@extends('layout.master')
@extends('layout.sidebar')

@section('container')

<section class="section">
  <br>
  <div class="section-header">
    <h1>Tambah Data Matapelajaran</h1>
  </div>
  <div class="card">
    <div class="card-body">
      <form action="{{route('mapel.store')}}" method="POST">
        @csrf
        <div class="form-group">
          <label>MataPelajaran</label>
          <input type="text" name="matapelajaran" class="form-control" placeholder="Nama Matapelajaran" required>
        </div>
        <div class="form-group">
          <a href="{{route('mapel.index')}}" class="btn btn-icon icon-left btn-warning">Kembali</a>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</section>

@endsection