routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapelController;
use App\Http\Controllers\DataguruController;
use App\Http\Controllers\DatakelasController;
use App\Http\Controllers\TahunajaranController;
use App\Http\Controllers\AngkatanController;
use App\Http\Controllers\DatasiswaController;
use App\Http\Controllers\SesiController;
use App\Http\Controllers\GurumapelController;
use App\Http\Controllers\RombelController;
use App\Http\Controllers\DatajadwalController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\JadwalguruController;
use App\Http\Controllers\PresensiController;
use App\Http\Controllers\DatakepegController;
use App\Http\Controllers\PendinformalController;
use App\Http\Controllers\PendformalController;
use App\Http\Controllers\RpekerjaanController;
use App\Http\Controllers\PenghargaanController;
use App\Http\Controllers\KetorganisasiController;
use App\Http\Controllers\KetlainController;
use App\Http\Controllers\WalikelasController;
use App\Http\Controllers\NilaiController;
use App\Http\Controllers\DatauserController;
use App\Http\Controllers\JadwalsiswaController;
use App\Http\Controllers\KelasguruController;
use App\Http\Controllers\KontaksiswaController;
use App\Http\Controllers\NilaisiswaController;
use App\Http\Controllers\PresensisiswaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RkeluargaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

//login
// Route::resource('login', AuthController::class);
Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('aktivasi_akun', 'App\Http\Controllers\AuthController@aktivasi_akun')->name('aktivasi_akun');
Route::get('lupapassword', 'App\Http\Controllers\AuthController@index_lupapassword')->name('lupapassword');
Route::post('forgot_password', 'App\Http\Controllers\AuthController@forgot_password')->name('forgot_password');
Route::get('reset_password', 'App\Http\Controllers\AuthController@reset_password')->name('reset_password');
Route::post('new_password', 'App\Http\Controllers\AuthController@new_password')->name('new_password');


//auth
//auth -> admin || guru || siswa

Route::group(['middleware' => ['auth']], function () {
    Route::resource('profile', ProfileController::class);
    Route::group(['middleware' => ['Cek_login:admin']], function () {
        Route::get('dashboardadmin', 'App\Http\Controllers\AdminController@index');
        //route admin
        Route::resource('dashboardadmin', AdminController::class);
        //admin : Mapel
        Route::resource('mapel', MapelController::class);
        //admin : guru
        Route::resource('guru', DataguruController::class);
        //admin : siswa
        Route::resource('siswa', DatasiswaController::class);
        //admin : kelas
        Route::resource('kelas', DatakelasController::class);
        //admin : angkatan
        Route::resource('angkatan', AngkatanController::class);
        //admin : tahun ajaran
        Route::resource('tahunajaran', TahunajaranController::class);
        //admin : sesi
        Route::resource('sesi', SesiController::class);
        //admin : guru mapel
        Route::resource('gurumapel', GurumapelController::class);
        //admin : rombel
        Route::resource('rombel', RombelController::class);
        //admin : jadwal
        Route::resource('jadwal', DatajadwalController::class);
        Route::get('hapus', 'App\Http\Controllers\DataJadwalController@hapus')->name('jadwal.hapus');
        //admin : walikelas
        Route::resource('walikelas', WalikelasController::class);
        //admin : kepegawaian
        Route::resource('kepeg', DatakepegController::class);
        //admin : user
        Route::resource('datauser', DatauserController::class);
    });
    Route::group(['middleware' => ['Cek_login:guru']], function () {
        Route::get('dashboardguru', 'App\Http\Controllers\GuruController@index')->name('dashboardguru.index');
        Route::resource('jadwalguru', JadwalguruController::class);
        Route::resource('presensi', PresensiController::class);
        Route::get('rekapharian', 'App\Http\Controllers\PresensiController@rekapharian')->name('presensi.rekapharian');
        Route::get('allrekap', 'App\Http\Controllers\PresensiController@allrekap')->name('presensi.allrekap');
        Route::get('indexallrekap', 'App\Http\Controllers\PresensiController@indexallrekap')->name('presensi.indexallrekap');
        Route::resource('kepegawaian', DatakepegController::class);
        Route::resource('pendinformal', PendinformalController::class);
        Route::resource('pendformal', PendformalController::class);
        Route::resource('riwayatpekerjaan', RpekerjaanController::class);
        Route::resource('penghargaan', PenghargaanController::class);
        Route::resource('ketorganisasi', KetorganisasiController::class);
        Route::resource('ketlain', KetlainController::class);
        Route::resource('nilai', NilaiController::class);
        Route::resource('kelasguru', KelasguruController::class);
        Route::resource('riwayatkeluarga', RkeluargaController::class);
        Route::resource('infokontak', KontaksiswaController::class);
        Route::resource('datanilaisiswa', NilaiController::class);
        Route::post('deskripsi', 'App\Http\Controllers\NilaiController@deskripsi')->name('datanilaisiswa.deskripsi');
    });
    Route::group(['middleware' => ['Cek_login:siswa']], function () {
        Route::get('dashboardsiswa', 'App\Http\Controllers\SiswaController@index')->name('dashboardsiswa.index');
        Route::resource('jadwalsiswa', JadwalsiswaController::class);
        Route::resource('presensisiswa', PresensisiswaController::class);
        Route::resource('nilaisiswa', NilaisiswaController::class);
        Route::get('cetakrapot', 'App\Http\Controllers\NilaisiswaController@cetakpdf')->name('nilaisiswa.cetakrapot');
    });
});

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('siswa.siswa');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/siswa/cetak.blade.php
@php
use Illuminate\Support\Facades\DB;
@endphp
<!DOCTYPE html>
<html>

<head>
    <style>
        .with-border {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        .with-border td {
            border: 1px solid black;
            text-align: left;
            padding: 8px;
        }

        /* tr:nth-child(even) {
  background-color: #dddddd;
} */
        /* table,
        th,
        td {
            font-family: arial, sans-serif;
            border: 1px solid black;
            border-collapse: collapse;
            padding: 5px;
        } */
    </style>
    <title>Hi</title>
</head>

<body>
    <div class="card-body">
        <div class="card-header">
            <div>
                <table style="width: 50%; float: left">
                    <tr>
                        <th style="border: 0px; text-align:left">Nama Sekolah</th>
                        <td>: Muhammadiyah Boarding School</td>
                    </tr>
                    <tr>
                        <th style="border: 0px; text-align:left">Alamat</th>
                        <td>: Jetis - Ponorogo</td>
                    </tr>
                    <tr>
                        <th style="border: 0px; text-align:left">Nama</th>
                        <td>: {{$siswa->nama}}</td>
                    </tr>
                    <tr>
                        <th style="border: 0px; text-align:left">NISN</th>
                        <td>: {{$siswa->nisn}}</td>
                    </tr>
                </table>
                <table style="width: 50%; float: right; text-align:left">
                    <tr>
                        <th style="border: 0px; text-align:left">Kelas</th>
                        <td>: {{$siswa->nama_kelas}}</td>
                    </tr>
                    <tr>
                        <th style="border: 0px; text-align:left">Semester</th>
                        <td>: {{$siswa->semester}}</td>
                    </tr>
                    <tr>
                        <th style="border: 0px; text-align:left">Tahun pelajaran</th>
                        <td>: {{$siswa->tahun}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <br>
        <br>
        <div class="table">
            <table class="with-border" style="margin-top: 150px">
                <thead>
                    <tr>
                        <td colspan="2" rowspan="2" style="text-align: center">Mata Pelajaran</td>
                        <td rowspan="2" colspan="2" style="text-align: center">Pengetahuan</td>
                        <td rowspan="2" colspan="2" style="text-align: center">Keterampilan</td>
                        <td colspan="2" style="text-align: center">Sikap Spiritual dan Sosial</td>
                    </tr>
                    <tr>
                        <td>Dalam Mapel</td>
                        <td>Antar Mapel</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="2">Kelompok 1</td>
                        <td>Angka</td>
                        <td>Huruf</td>
                        <td>Angka</td>
                        <td>Huruf</td>
                        <td>SB/B/C/K</td>
                        <td>Deskripsi</td>
                    </tr>
                    @php
                    $jumlah = 0;
                    foreach($data as $i => $item){
                    $jumlah++;
                    }
                    $isideskripsi = '';
                    @endphp
                    @foreach ($data as $i => $item)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $item->matapelajaran }}</td>
                        <td>
                            @php
                            $jumlah_bobot_pengetahuan = $item->bobot_np + $item->bobot_nuts + $item->bobot_nuas;
                            @endphp
                            {{ $rapot =
                            ((($item->np*$item->bobot_np)+($item->nuts*$item->bobot_nuts)+($item->nuas*$item->bobot_nuas))/$jumlah_bobot_pengetahuan)/100*$jumlah_bobot_pengetahuan
                            }}
                            @php
                            $konversi = DB::table('konversi_nilai')
                            ->where([
                            ['batas_bawah', '<', $rapot], ['batas_atas', '>=' , number_format($rapot,2)], ])->
                                where('jenis','nm')
                                ->first();
                                @endphp</td>
                        <td>{{$konversi->konversi}}</td>
                        <td>
                            @php
                            $jumlah_bobot_ketrampilan = $item->bobot_praktik + $item->bobot_porto + $item->bobot_proyek;
                            @endphp
                            {{ $rapot =
                            ((($item->nilai_praktik*$item->bobot_praktik)+($item->nilai_porto*$item->bobot_porto)+($item->nilai_proyek*$item->bobot_proyek))/$jumlah_bobot_ketrampilan)/100*$jumlah_bobot_ketrampilan}}
                            @php
                            $konversi = DB::table('konversi_nilai')
                            ->where([
                            ['batas_bawah', '<', $rapot], ['batas_atas', '>=' , number_format($rapot,2)], ])->
                                where('jenis','nm')
                                ->first();
                                @endphp

                        </td>
                        <td>{{$konversi->konversi}}</td>
                        <td>
                            @php
                            $konversi = DB::table('konversi_nilai')
                            ->where([
                            ['batas_bawah', '<=', $item->nilai_sikapmapel], ['batas_atas', '>' ,
                                $item->nilai_sikapmapel], ]) ->where('jenis','ns')
                                ->first();
                                // print_r($konversi);exit;
                                echo $konversi->konversi;
                                @endphp
                        </td>
                        @if ($i==1)
                        <td rowspan={{$countdatanilai}}>
                            @php
                            if($isideskripsi == ''){
                            echo $deskripsi->deskripsi;
                            $isideskripsi=$deskripsi->deskripsi;
                            }
                            @endphp
                        </td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="table">
                <table class="with-border" style="margin-top: 30px">
                    <thead>
                        <tr>
                            <td style="text-align: center">Kegiatan Ektrakurikuler</td>
                            <td style="text-align: center">Nilai</td>
                            <td style="text-align: center">Keterangan</td>
                        </tr>
                    </thead>
                    <tbody>
                        @for ($i = 0; $i < 3; $i++) <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            </tr>
                            @endfor
                    </tbody>
                </table>
            </div>

            <div class="table" style="width: 50%">
                <table class="with-border" style="margin-top: 30px">
                    <thead>
                        <tr>
                            <td style="text-align: center">Ketidakhadiran</td>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                        $alpha=0;
                        $ijin=0;
                        @endphp
                        @foreach ($countpresensi as $p)
                        $alpha += $p->alpha;
                        $ijin += $p->ijin;
                        @endforeach
                        <tr>
                            <td>Ijin/Sakit<span style="padding: 100px">= {{$ijin}}</span></td>
                        </tr>
                        <tr>
                            <td>Alpha<span style="padding: 120px">= {{$alpha}}</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="row">
                <div>
                    <table style="width: 500px; float: left; margin-top: 30px">
                        <tr>
                            <td style="border: 0px; text-align:left">Mengetahui :</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="border: 0px; text-align:left">Orangtua/Wali</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="border: 0px; text-align:left">
                                <hr style="width: 170px; float:left; margin-top: 90px">
                            </td>
                            <td></td>
                        </tr>
                    </table>
                    <table style="width: 350px; float: left; text-align:left; margin-top: 30px">
                        <tr>
                            <td style="border: 0px; text-align:left">
                                .....................,..............20....</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="border: 0px; text-align:left;">Wali Kelas,</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="border: 0px; height:20px;;"></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="border: 0px; height:140px;;">
                                {{$walikelas->nama}}
                                <hr style="width: 170px; float:left; margin-top:70px"><br>
                                NIP {{$walikelas->nip}}
                            </td>
                            <td></td>
                        </tr>
                    </table>

                </div>
            </div>
            {{-- <div class="row">
                <div class="col-sm-12">
                    <hr style="width: 50%; float:left; margin-top: 80px">
                    <div style="border: 0px; text-align:left; margin-top: 90px">
                        NIP ....................................
                    </div>
                </div>
            </div> --}}
        </div>


        {{-- @foreach ($data as $item)
        Mapel : {{ $item->matapelajaran }} ||
        Pengetahuan : {{ $rapot =
        (($item->np*$item->bobot_np)+($item->nuts*$item->bobot_nuts)+($item->nuas*$item->bobot_nuas))/4 }} || Konversi :
        {{
        $rapot/100*4 }}
        <br />
        @endforeach --}}
</body>

</html>

resources/views/siswa/profilesiswa.blade.php
@extends('layout.master')
@extends('layout.sidebarsiswa')

@section('container')


<section class="section">
    <br>
    <div class="section-header">
        <h1>Profile</h1>
    </div>
    <div class="section-body">
        <div class="row mt-sm-12">
            <div class="col-6 col-md-12">

                <form method="post" class="needs-validation"
                    action="{{route('profile.update', ['profile'=>$data->id_user])}}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')


            </div>
            <div class="col-12 col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Edit Profile</h4>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-6 col-12">
                                <label>Email</label>
                                <input type="text" name="email" class="form-control" value="{{$data->email}}"
                                    required="">
                                <div class="invalid-feedback">
                                    Please fill in the first name
                                </div>
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label>Username</label>
                                <input type="text" name="username" class="form-control" value="{{$data->username}}"
                                    required="">
                                <div class="invalid-feedback">
                                    Please fill in the last name
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>NISN</label>
                                    <input type="text" name="nisn" class="form-control" value="{{$data->nisn}}"
                                        required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control" value="{{$data->nama}}"
                                        required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Tempat Lahir</label>
                                    <input type="text" name="tempat_lahir" class="form-control"
                                        value="{{$data->tempat_lahir}}" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Tanggal Lahir</label>
                                    <input type="date" name="tgl_lahir" class="form-control"
                                        value="{{$data->tgl_lahir}}" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="d-block">Jenis Kelamin</label>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="jk" id="jk1"
                                            value="laki-laki" {{$data->jk == 'laki-laki' ? 'checked' : ''}}>
                                        <label class="form-check-label" for="jk1">
                                            Laki-laki
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="jk" id="jk2"
                                            value="perempuan" {{$data->jk == 'perempuan' ? 'checked' : ''}}>
                                        <label class="form-check-label" for="jk2">
                                            Perempuan
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Agama</label>
                                    <select name="agama" class="form-control">
                                        <option></option>
                                        <option value="islam" {{$data->agama == 'islam' ? 'selected' : ''}}>Islam
                                        </option>
                                        <option value="katholik" {{$data->agama == 'katholik' ? 'selected' :
                                            ''}}>Katholik</option>
                                        <option value="kristen" {{$data->agama == 'kristen' ? 'selected' :
                                            ''}}>Kristen</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="alamat">Alamat</label>
                                    <textarea name="alamat" class="form-control" id="alamat">
                                            {{$data->alamat}}
                                        </textarea>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Kodepos</label>
                                    <input type="text" name="kodepos" class="form-control" value="{{$data->kodepos}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Anak Ke-</label>
                                    <input type="text" name="anak_ke" class="form-control" value="{{$data->anak_ke}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Jumlah Saudara</label>
                                    <input type="text" name="jml_saudara" class="form-control"
                                        value="{{$data->jml_saudara}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Pendidikan Terakhir</label>
                                    <input type="text" name="akhir_pendidikan" class="form-control"
                                        value="{{$data->akhir_pendidikan}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Asal Sekolah</label>
                                    <input type="text" name="asal_sekolah" class="form-control"
                                        value="{{$data->asal_sekolah}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Tahun diterima</label>
                                    <input type="text" name="thn_terima" class="form-control"
                                        value="{{$data->thn_terima}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Riwayat Penyakit</label>
                                    <input type="text" name="penyakit_diderita" class="form-control"
                                        value="{{$data->penyakit_diderita}}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Foto</label>
                                    <input type="file" name="foto" class="form-control">
                                    <img alt="image" src="{{URL::to('/uploads').'/'.$data->foto}}"
                                        class="profile-widget-picture" style="width:35%">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                        </div>
                        </form>
                    </div>
                </div>

            </div>
</section>



@endsection

resources/views/siswa/siswa.blade.php
@extends('layout.master')
@extends('layout.sidebarsiswa')

@section('container')
<section class="section">
    <br>
    <div class="section-header">
        <h1>Dashboard</h1>
    </div>
    @if(session('error_akses'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{session('error_akses')}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    <div class="alert alert-success alert-dismissible fade show" role="alert">

        Selamat Datang di Sistem Akademik Muhammadiyah Boarding School sebagai siswa.
        {{-- <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button> --}}
    </div>

    {{-- <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="card card-statistic-1">
                <div class="card-icon bg-danger">
                    <i class="fas fa-book-open"></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4>Absensi</h4>
                    </div>
                    <div class="card-body">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <div class="card card-statistic-1">
                <div class="card-icon bg-success">
                    <i class="fas fas fa-bookmark"><a href="{{route('mapel.index')}}"></a></i>
                </div>
                <div class="card-wrap">
                    <div class="card-header">
                        <h4>Total Mapel</h4>
                    </div>
                    <div class="card-body">

                    </div>
                </div>
            </div>
        </div>
    </div> --}}

    @endsection